name: rag
services:
  langfuse:
    image: langfuse/langfuse:2.69.0
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: 'postgres:5432'
      DATABASE_NAME: 'langfuse'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'test!123PW_'
      NEXTAUTH_SECRET: 'mysecret'
      SALT: 'mysalt'
      NEXTAUTH_URL: 'http://localhost:3000'
      TELEMETRY_ENABLED: false
      LANGFUSE_DEFAULT_PROJECT_ID: kicwa
      LANGFUSE_DEFAULT_PROJECT_ROLE: 'ADMIN'


  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'test!123PW_'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
