[tool.poetry]
name = "kic-web-assistant"
version = "0.1.0"
description = "System to guide the users of ki-campus.org"
authors = ["Jonas Bremer <jonas.bremer@scieneers.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
qdrant-client = "~1.6.9"
openai = "~1.3.6"
langchain = "~0.0.344"
lark = "~1.1.8"
torch = "~2.1.1"
accelerate = "~0.24.1"
transformers = "~4.35.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "~6.26.0"
ipywidgets = "~8.1.1"
pytest = "~7.4.3"

[tool.poetry.group.llmhosting.dependencies]
google-cloud-aiplatform = "~1.36.4"

[tool.poetry.group.data_loader.dependencies]
requests = "~2.31.0"
pydantic = "~2.5.2"
beautifulsoup4 = "~4.12.2"

[tool.poetry.group.frontend.dependencies]
streamlit = "~1.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
