[tool.poetry]
name = "kic-web-assistant"
version = "0.1.0"
description = "System to guide the users of ki-campus.org"
authors = ["Jonas Bremer <jonas.bremer@scieneers.de>"]
readme = "README.md"
packages = [{include = "kic_web_assistant"}]

[tool.poetry.dependencies]
python = "~3.11"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
