version: '3'

vars:
  # Build for different architecture in case of arm processors
  TARGET: "linux"
  REGISTRY: "kicacrdev.azurecr.io"

tasks:
  print-vars:
    cmds:
      - |
        echo "TARGET: {{ .TARGET }}"
        echo "REGISTRY: {{ .REGISTRY }}"

  build-frontend:
    desc: Build the docker image for the streamlit frontend
    vars:
      VERSION:
        sh: |
          if [ -n "{{.CLI_ARGS}}" ]; then
            echo "{{.CLI_ARGS}}"
          else
            git rev-parse --short HEAD
          fi
    cmds:
      - echo "Building frontend with version {{.VERSION}}"
      - |
        {{ if eq .TARGET "linux" }}
          docker buildx build --load --platform linux/amd64 -t {{ .REGISTRY }}/app:{{.VERSION}} -f src/frontend/Dockerfile .
        {{ else }}
          docker build -t {{ .REGISTRY }}/app:{{.VERSION}} -f src/frontend/Dockerfile .
        {{ end }}

  build-api:
    desc: Build the docker image for the chatbot Rest API
    vars:
      VERSION:
        sh: |
          if [ -n "{{.CLI_ARGS}}" ]; then
            echo "{{.CLI_ARGS}}"
          else
            git rev-parse --short HEAD
          fi
    cmds:
      - echo "Building API with version {{.VERSION}}"
      - |
        {{ if eq .TARGET "linux" }}
          docker buildx build --load --platform linux/amd64 -t {{ .REGISTRY }}/rest-api:{{.VERSION}} -f src/api/Dockerfile .
        {{ else }}
          docker build -t {{ .REGISTRY }}/rest-api:{{.VERSION}} -f src/api/Dockerfile .
        {{ end }}

  build-embedder:
    desc: Build the docker image for the embedder API
    vars:
      VERSION:
        sh: |
          if [ -n "{{.CLI_ARGS}}" ]; then
            echo "{{.CLI_ARGS}}"
          else
            git rev-parse --short HEAD
          fi
    cmds:
      - echo "Building embedder with version {{.VERSION}}"
      - |
        {{ if eq .TARGET "linux" }}
          docker buildx build --load --platform linux/amd64 -t {{ .REGISTRY }}/embedder:{{.VERSION}} -f src/embedder/Dockerfile .
        {{ else }}
          docker build -t {{ .REGISTRY }}/embedder:{{.VERSION}} -f src/embedder/Dockerfile .
        {{ end }}

  push-frontend:
    desc: Push the frontend docker image. Version defaults to git commit hash if not provided.
    vars:
      VERSION:
        sh: |
          if [ -n "{{.CLI_ARGS}}" ]; then
            echo "{{.CLI_ARGS}}"
          else
            git rev-parse --short HEAD
          fi
    cmds:
      - echo "Pushing frontend with version {{.VERSION}}"
      - docker push {{ .REGISTRY }}/app:{{.VERSION}}

  push-api:
    desc: Push the API docker image. Version defaults to git commit hash if not provided.
    vars:
      VERSION:
        sh: |
          if [ -n "{{.CLI_ARGS}}" ]; then
            echo "{{.CLI_ARGS}}"
          else
            git rev-parse --short HEAD
          fi
    cmds:
      - echo "Pushing API with version {{.VERSION}}"
      - docker push {{ .REGISTRY }}/rest-api:{{.VERSION}}

  push-latest-images:
    desc: Pushes the docker images. Make sure to only push amd64 images. Version defaults to git commit hash if not provided.
    vars:
      VERSION:
        sh: |
          if [ -n "{{.CLI_ARGS}}" ]; then
            echo "{{.CLI_ARGS}}"
          else
            git rev-parse --short HEAD
          fi
    cmds:
      - echo "Pushing images with version {{.VERSION}}"
      - docker push {{ .REGISTRY }}/app:{{.VERSION}}
      - docker push {{ .REGISTRY }}/rest-api:{{.VERSION}}

  az-login:
    desc: Login to azure using azure-cli
    cmds:
      - az login --tenant c6ff58bc-993e-4bdb-8d10-6013e2cd361f --scope https://graph.microsoft.com/.default
      - az acr login --name kicacrdev.azurecr.io
